language: objective-c
osx_image: xcode7.3
xcode_workspace: EverliveSdkTests.xcworkspace
xcode_scheme: EverliveSdkTestsTests
xcode_sdk: iphonesimulator9.3
before_install:
 - brew update
 - brew install tailor

script: set -o pipefail && xcodebuild test -workspace EverliveSdkTests.xcworkspace -scheme EverliveSdkTestsTests -sdk iphonesimulator9.3
